apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-ca-operator-catalog-subscription
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.cognos_analytics.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-ca-operator
  source: ibm-ca-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}