---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.ibm_cert_manager.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argocd_namespace }}


