block_storage_class: ''
cpd_instance_namespace: cpd-instance
cpd_operators_namespace: cpd-operator
cpd_release: 5.1.0
file_storage_class: ''
pre_sync_hook_sa: cpd-pre-sync-sa
pre_sync_job_image: icr.io/cpopen/cpd/olm-utils-v3:latest
wkc:
  catsrc_display_name: ibm-wkc-5.1.0+20241120.123810.425
  catsrc_image: icr.io/cpopen/ibm-cpd-wkc-operator-catalog@sha256:c03e3f8f9c9f399fd2cda82ee459edce36579aada853d23653957601c8eb50a0
  cr_name: wkc-cr
  cr_version: 5.1.0
  custom_spec: {}
  dependencies: ccs,db2aaservice,db2u,analyticsengine,opencontent_elasticsearch,opencontent_fdb,datastage_ent
  enable_knowledge_graph: false
  sub_channel: v7.0
  wkc_db2u_set_kernel_params: true
