#TODO: might need to move this to a "cluster-admin" chart or root chart for separation of cluster admin permission
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nss-managed-role-from-{{ .Values.cpd_operators_namespace }}
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    managed-by: nss
rules:
  - apiGroups:
    - "*"
    resources:
    - "*"
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
    - deletecollection
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nss-managed-role-from-{{ .Values.cpd_operators_namespace }}
  namespace: {{ .Values.cpd_instance_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    managed-by: nss
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
    apiGroups:
      - '*'
    resources:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nss-managed-role-from-{{ .Values.cpd_operators_namespace }}
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    managed-by: nss
subjects:
  - kind: ServiceAccount
    name: ibm-namespace-scope-operator
    namespace: {{ .Values.cpd_operators_namespace }}
roleRef:
  kind: Role
  name: nss-managed-role-from-{{ .Values.cpd_operators_namespace }}
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nss-managed-role-from-{{ .Values.cpd_operators_namespace }}
  namespace: "{{ .Values.cpd_instance_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    managed-by: nss
subjects:
  - kind: ServiceAccount
    name: ibm-namespace-scope-operator
    namespace: "{{ .Values.cpd_operators_namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nss-managed-role-from-{{ .Values.cpd_operators_namespace }}