---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: common-service
  namespace: "{{ .Values.cpd_operators_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  targetNamespaces:
    - {{ .Values.cpd_operators_namespace }}
