apiVersion: operator.ibm.com/v1
kind: NamespaceScope
metadata:
  name: cpd-operators
  namespace: "{{ .Values.cpd_operators_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: ServerSideApply=true #use server side apply as partial patching
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  csvInjector:
    enable: true
  license:
    accept: true
  namespaceMembers:
    - "{{ .Values.cpd_operators_namespace }}"
    - "{{ .Values.cpd_instance_namespace }}"
  restartLabels:
    intent: projected