apiVersion: datarefinery.cpd.ibm.com/v1beta1
kind: DataRefinery
metadata:
  name: datarefinery-cr
  namespace: {{ .Values.cpd_instance_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: ServerSideApply=true #use server side apply as partial patching
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  autoScaleConfig: {{ .Values.datarefinery.auto_scale_config }}
  blockStorageClass: {{ .Values.block_storage_class }}
  docker_registry_prefix: cp.icr.io/cp/cpd
  fileStorageClass: {{ .Values.file_storage_class }}
  license:
    accept: true
    license: Enterprise
  scaleConfig: {{ .Values.datarefinery.scale_config }}
  storageClass: {{ .Values.block_storage_class }}
  version: {{ .Values.datarefinery.cr_version }}