cpd_release: 5.0.0
cpd_operators_namespace: "cpd-operator"
cpd_instance_namespace: "cpd-instance"
block_storage_class: ""
file_storage_class: ""
pre_sync_hook_sa: "cpd-pre-sync-sa"
pre_sync_job_image: icr.io/cpopen/cpd/olm-utils-v3:latest
ikc_standard:
  dependencies: cpd_platform,ccs,analyticsengine,datarefinery,watsonx_ai_ifm,db2aaservice
  sub_channel: v5.0
  cr_name: ikc-standard-cr
  cr_version: 5.0.0
  catsrc_display_name: CPD IKC
  catsrc_image: icr.io/cpopen/ibm-cpd-knowledge-catalog-operator-catalog@sha256:21fdcc4ec8fb7d46dd2005067bc14c6b027f185fa9ed86f64ed36a03b30f0e77
  enable_semantic_automation: false