apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-cert-manager-operator
  namespace: "{{ .Values.ibm_cert_manager.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: 
  upgradeStrategy: Default