apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-db2u-operator
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.db2u.sub_channel }}
  installPlanApproval: Automatic
  name: db2u-operator
  source: ibm-db2uoperator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}