apiVersion: v1
data:
  DB2U_RUN_WITH_LIMITED_PRIVS: "{{ .Values.db2u.DB2U_RUN_WITH_LIMITED_PRIVS }}"
kind: ConfigMap
metadata:
  name: db2u-product-cm
  namespace: {{ .Values.cpd_instance_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"