---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.scheduler.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argocd_namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-sub-sa
  namespace: {{ .Values.scheduler.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler-sub-role
  namespace: {{ .Values.scheduler.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules: 
- apiGroups: ["operators.coreos.com"]
  resources:
  - subscriptions
  - clusterserviceversions
  verbs:
  - get
  - list
  - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler-sub-rb
  namespace: {{ .Values.scheduler.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
  - kind: ServiceAccount
    name: scheduler-sub-sa
    namespace: {{ .Values.scheduler.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheduler-sub-role