cpd_release: 5.0.0
cpd_operators_namespace: "cpd-operator"
cpd_instance_namespace: "cpd-instance"
block_storage_class: ""
file_storage_class: ""
pre_sync_hook_sa: "cpd-pre-sync-sa"
pre_sync_job_image: icr.io/cpopen/cpd/olm-utils-v3:latest
opencontent_elasticsearch:
  catsrc_display_name: ibm-elasticsearch-operator-1.1.2153
  catsrc_image: icr.io/cpopen/opencontent-elasticsearch-operator-catalog@sha256:755b5177805a37c1dbfa450ccd4e8e9cd4798b73835b07663e3915b9c7efadc4