block_storage_class: ''
cpd_instance_namespace: cpd-instance
cpd_operators_namespace: cpd-operator
cpd_release: 5.1.0
db2oltp:
  catsrc_display_name: ibm-db2oltp-5.1.0+20241107.162510.2667.3736
  catsrc_image: icr.io/cpopen/ibm-db2oltp-cp4d-operator-catalog@sha256:620da0d733f653d3f3aa0f9fe11d12995dab1e827e3eccf88e330dadd3875434
  cr_name: db2oltp-cr
  cr_version: 5.1.0
  dependencies: cpd_platform
  sub_channel: v7.0
file_storage_class: ''
pre_sync_hook_sa: cpd-pre-sync-sa
pre_sync_job_image: icr.io/cpopen/cpd/olm-utils-v3:latest
