block_storage_class: ''
cpd_instance_namespace: cpd-instance
cpd_operators_namespace: cpd-operator
cpd_release: 5.1.0
factsheet:
  catsrc_display_name: ibm-factsheet-5.0.0+20241120.161527.134
  catsrc_image: icr.io/cpopen/ibm-cpd-factsheet-operator-catalog@sha256:79ef0a5b84cfd5002d3843584e4e4b08af653e37e529abf7f5aabcc3858f8f30
  cr_version: 5.1.0
  dependencies: ccs
  sub_channel: v5.0
file_storage_class: ''
pre_sync_hook_sa: cpd-pre-sync-sa
pre_sync_job_image: icr.io/cpopen/cpd/olm-utils-v3:latest
