apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-fdb-operator
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.opencontent_fdb.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-opencontent-foundationdb
  source: ibm-fdb-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}