cpd_release: 5.0.0
cpd_operators_namespace: "cpd-operator"
cpd_instance_namespace: "cpd-instance"
block_storage_class: ""
file_storage_class: ""
pre_sync_hook_sa: "cpd-pre-sync-sa"
pre_sync_job_image: icr.io/cpopen/cpd/olm-utils-v3:latest
canvasbase:
  catsrc_display_name: ibm-canvasbase-9.0.0+20240521.225150.28
  catsrc_image: icr.io/cpopen/ibm-cpd-canvasbase-operator-catalog@sha256:2821b30d15d53e035ffe33598e04a3d7d16efee8c917a53f516772060c88964b
  sub_channel: v9.0