apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-planning-analytics-subscription
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.planning_analytics.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-planning-analytics-operator
  source: ibm-planning-analytics-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}