apiVersion: pa.cpd.ibm.com/v1
kind:  PAService
metadata:
  name: ibm-planning-analytics-service
  namespace: {{ .Values.cpd_instance_namespace }}
  labels:
    app.kubernetes.io/instance: ibm-planning-analytics-service
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: planning_analytics
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: ServerSideApply=true #use server side apply as partial patching
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
    license: Enterprise
{{- if not (eq .Values.block_storage_class "") }}
  blockStorageClass: {{ .Values.block_storage_class }}
{{- end}}
{{- if not (eq .Values.file_storage_class "") }}
  fileStorageClass: {{ .Values.file_storage_class }}
{{- end}}
  version: {{ .Values.planning_analytics.cr_version }}