apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cpd-ae-operator
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.analyticsengine.sub_channel }}
  installPlanApproval: Automatic
  name: analyticsengine-operator
  source: ibm-cpd-ae-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}