block_storage_class: ''
cpd_instance_namespace: cpd-instance
cpd_operators_namespace: cpd-operator
cpd_release: 5.1.0
datastage_ent:
  catsrc_display_name: ibm-datastage-enterprise-9.0.0+20241113.135627.2825
  catsrc_image: icr.io/cpopen/ds-operator-catalog@sha256:e57cc59ae143667b88c550a0fdc851ae75424125c7f18284561c77afa495e4f2
  cr_name: datastage
  cr_version: 5.1.0
  dependencies: ccs
  sub_channel: v7.0
file_storage_class: ''
pre_sync_hook_sa: cpd-pre-sync-sa
pre_sync_job_image: icr.io/cpopen/cpd/olm-utils-v3:latest
