{{- range $i, $kind := .Values.ws_runtimes.additional_runtime_kind }}
---
apiVersion: ws.cpd.ibm.com/v1beta1
kind: NotebookRuntime
metadata:
  name: ibm-cpd-ws-runtime-{{ $kind }}
  namespace: {{ $.Values.cpd_instance_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: ServerSideApply=true #use server side apply as partial patching
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  kind: ibm-cpd-ws-runtime-{{ $kind }}
  license:
    accept: true
  version: {{ $.Values.ws_runtimes.cr_version }}
{{- end}}