apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cpd-syntheticdata-operator-catalog-subscription
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.syntheticdata.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-cpd-syntheticdata
  source: ibm-syntheticdata-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}