apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-redis-cp-operator
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.ibm_redis_cp.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-redis-cp
  source: ibm-redis-cp-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}