apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-watson-openscale-operator-subscription
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.openscale.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-cpd-wos
  source: ibm-openscale-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}