apiVersion: wos.cpd.ibm.com/v1
kind:  WOService
metadata:
  name: aiopenscale
  namespace: {{ .Values.cpd_instance_namespace }}
  labels:
    app.kubernetes.io/instance: aiopenscale
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: openscale
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: ServerSideApply=true #use server side apply as partial patching
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
    license: Enterprise
  version: {{ .Values.openscale.cr_version }}
{{- if not (eq .Values.block_storage_class "") }}
  blockStorageClass: {{ .Values.block_storage_class }}
{{- end}}
{{- if not (eq .Values.file_storage_class "") }}
  fileStorageClass: {{ .Values.file_storage_class }}
{{- end}}