---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cpd-ccs-operator
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.ccs.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-cpd-ccs
  source: ibm-cpd-ccs-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}