apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cpd-knowledge-catalog-operator-catalog-subscription
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.ikc_standard.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-cpd-knowledge-catalog
  source: ibm-cpd-knowledge-catalog-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}