apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-licensing-operator-app
  namespace: {{ .Values.ibm_licensing.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: 
  targetNamespaces:
    - {{ .Values.ibm_licensing.namespace }}
