apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-licensing-operator-app
  namespace: {{ .Values.ibm_licensing.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: {{ .Values.ibm_licensing.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-licensing-operator-app
  source: ibm-licensing-catalog
  sourceNamespace: {{ .Values.ibm_licensing.namespace }}