cpd_release: 5.0.0
cpd_operators_namespace: "cpd-operator"
cpd_instance_namespace: "cpd-instance"
block_storage_class: ""
file_storage_class: ""
pre_sync_hook_sa: "cpd-pre-sync-sa"
pre_sync_job_image: icr.io/cpopen/cpd/olm-utils-v3:latest
db2aaservice:
  sub_channel: v6.0
  cr_name: db2aaservice-cr
  cr_version: 5.0.0
  dependencies: cpd_platform
  catsrc_display_name: ibm-db2aaservice-5.0.0+20240521.164650.2491.3353
  catsrc_image: icr.io/cpopen/ibm-db2aaservice-cp4d-operator-catalog@sha256:a7f7f215c22725e631685173ec1e83a6a1ccb792dbcb14cd93988c1011b50f2a
