apiVersion: ikc.cpd.ibm.com/v1beta1
kind: IKCStandard
metadata:
  name: "{{ .Values.ikc_standard.cr_name }}"
  namespace: "{{ .Values.cpd_instance_namespace }}"
  labels:
    app.kubernetes.io/instance: ikc-standard-cr
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: ikc_standard
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: ServerSideApply=true #use server side apply as partial patching
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  version: "{{ .Values.ikc_standard.cr_version }}"
  license:
    accept: true
    license: Enterprise
{{- if not (eq .Values.block_storage_class "") }}
  blockStorageClass: {{ .Values.block_storage_class }}
{{- end}}
{{- if not (eq .Values.file_storage_class "") }}
  fileStorageClass: {{ .Values.file_storage_class }}
{{- end}}
  enableSemanticAutomation: "{{ .Values.ikc_standard.enable_semantic_automation }}" 