apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  namespace: {{ .Values.cpd_operators_namespace }}
  name: ibm-cpd-watsonx-governance-operator-catalog
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  sourceType: grpc
  image: {{ .Values.watsonx_governance.catsrc_image }}
  displayName: {{ .Values.watsonx_governance.catsrc_display_name }}
  publisher: IBM
  updateStrategy:
    registryPoll:
      interval: 45m