apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cpd-watsonx-governance-operator-catalog-subscription
  namespace: {{ .Values.cpd_operators_namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.watsonx_governance.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-cpd-watsonx-governance
  source: ibm-cpd-watsonx-governance-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}