apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  namespace: {{ .Values.cpd_operators_namespace }}
  name: ibm-cpd-ws-runtimes-operator-catalog
spec:
  displayName: {{ .Values.ws_runtimes.catsrc_display_name }}
  publisher: IBM
  image: {{ .Values.ws_runtimes.catsrc_image }}
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s