apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cpd-ws-runtimes-operator
  namespace: {{ .Values.cpd_operators_namespace }}
spec:
  channel: {{ .Values.ws_runtimes.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-cpd-ws-runtimes
  source: ibm-cpd-ws-runtimes-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}