apiVersion: ws.cpd.ibm.com/v1beta1
kind: NotebookRuntime
metadata:
  name: ibm-cpd-ws-runtime-241-py
  namespace: {{ .Values.cpd_instance_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: ServerSideApply=true #use server side apply as partial patching
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  kind: ibm-cpd-ws-runtime-{{ .Values.ws_runtimes.runtime_kind }}
  license:
    accept: true
  version: {{ .Values.ws_runtimes.cr_version }}