apiVersion: ds.cpd.ibm.com/v1
kind: DataStage
metadata:
  name: "{{ .Values.datastage_ent.cr_name }}"
  namespace: "{{ .Values.cpd_instance_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: ServerSideApply=true #use server side apply as partial patching
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
  version: "{{ .Values.datastage_ent.cr_version }}"
{{- if not (eq .Values.block_storage_class "") }}
  blockStorageClass: {{ .Values.block_storage_class }}
{{- end}}
{{- if not (eq .Values.file_storage_class "") }}
  fileStorageClass: {{ .Values.file_storage_class }}
{{- end}}