---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-utils-cm-sa
  namespace: {{ .Values.cpd_instance_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: olm-utils-cm-role
  namespace: {{ .Values.cpd_instance_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules: 
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: olm-utils-cm-rb
  namespace: {{ .Values.cpd_instance_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: olm-utils-cm-sa
    namespace: {{ .Values.cpd_instance_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: olm-utils-cm-role
---
apiVersion: batch/v1
kind: Job
metadata:
  name: olm-utils-cm-creation-job
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  namespace: {{ .Values.cpd_instance_namespace }}
  labels:
    cpd-release: {{ .Values.cpd_release }}
spec:
  template:
    spec:
      containers:
      - name: dep
        image: {{ .Values.pre_sync_job_image }}
        command:
          - bash
          - -c
          - |
            cd /opt/ansible/bin
            python3 create-olm-utils-cm.py --release={{ .Values.cpd_release }} --namespace={{ .Values.cpd_instance_namespace }}
      restartPolicy: Never
      serviceAccount: olm-utils-cm-sa