---
apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
  name: common-service
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true #use server side apply as partial patching
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
  operatorNamespace: {{ .Values.cpd_operators_namespace }}
  servicesNamespace: {{ .Values.cpd_instance_namespace }}
  size: {{ .Values.cpfs.size_profile }}
{{- if not (eq .Values.block_storage_class "") }}
  storageClass: {{ .Values.block_storage_class }}
{{- end}}
---
apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
  name: common-service
  namespace: {{ .Values.cpd_instance_namespace }}
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true #use server side apply as partial patching
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
  operatorNamespace: {{ .Values.cpd_operators_namespace }}
  servicesNamespace: {{ .Values.cpd_instance_namespace }}
  size: {{ .Values.cpfs.size_profile }}
{{- if not (eq .Values.block_storage_class "") }}
  storageClass: {{ .Values.block_storage_class }}
{{- end}}