---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cpd-operator
  namespace: "{{ .Values.cpd_operators_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  channel: "{{ .Values.cpd_platform.sub_channel }}"
  installPlanApproval: Automatic
  name: cpd-platform-operator
  source: cpd-platform
  sourceNamespace: "{{ .Values.cpd_operators_namespace }}"
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   {{- if .Values.is_upgrade_from_5_0_0 }}
#   name: ibm-platformui-operator
#   {{- end }}
#   {{- if not .Values.is_upgrade_from_5_0_0 }}
#   name: ibm-zen-operator
#   {{- end }}
#   namespace: "{{ .Values.cpd_operators_namespace }}"
#   annotations:
#     argocd.argoproj.io/sync-wave: "8"
#   labels:
#     operator.ibm.com/opreq-control: 'true'
# spec:
#   channel: "{{ .Values.zen.sub_channel }}"
#   installPlanApproval: Automatic
#   name: ibm-zen-operator
#   source: ibm-zen-operator-catalog
#   sourceNamespace: "{{ .Values.cpd_operators_namespace }}"
