apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: "{{ .Values.cpd_platform.cr_name }}"
  namespace: "{{ .Values.cpd_instance_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  version: "{{ .Values.cpd_platform.cr_version }}"
  license:
    accept: true
    license: Enterprise
{{- if not (eq .Values.block_storage_class "") }}
  blockStorageClass: {{ .Values.block_storage_class }}
{{- end}}
{{- if not (eq .Values.file_storage_class "") }}
  fileStorageClass: {{ .Values.file_storage_class }}
{{- end}}
{{- if .Values.cpd_platform.custom_spec }}
{{ .Values.cpd_platform.custom_spec | toYaml | indent 2 }}
{{- end }}