apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cpd-wspipelines-operator-catalog-subscription
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.ws_pipelines.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-cpd-wspipelines
  source: ibm-cpd-wspipelines-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}