---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.ibm_licensing.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argocd_namespace }}


