apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mdm-operator-subscription
  namespace: {{ .Values.cpd_operators_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.match360.sub_channel }}
  installPlanApproval: Automatic
  name: ibm-mdm
  source: ibm-mdm-operator-catalog
  sourceNamespace: {{ .Values.cpd_operators_namespace }}